import type { StoreLocale } from "@shared/catalog";

const en = {
  preparing: "Loading current products…", unavailable: "Products are temporarily unavailable.", retry: "Try again",
  loading: "Please wait", backStore: "Back to store", language: "Language", draft: "Unpaid order request",
  details: "Delivery details", shippingMethod: "Shipping estimate", review: "Review request", step: "Step",
  heading1: "Where would you like it delivered?", heading2: "Choose a shipping estimate.", heading3: "Review and save your request.",
  paused: "Online payment is not active. Saving a request charges nothing, does not reserve stock and does not arrange dispatch.",
  contact: "Contact", email: "Email address", marketing: "Send me product updates and offers.", addressTitle: "Shipping address",
  firstName: "First name", lastName: "Last name", country: "Country or region", address: "Street address",
  apartment: "Apartment, suite, etc. (optional)", city: "City", region: "State / region", postal: "Postal code", phone: "Phone",
  required: "This field is required.", invalidEmail: "Enter a valid email address.", invalidPhone: "Enter a valid phone number.",
  invalidPostal: "Enter a valid postal code.", invalidAddress: "Enter a complete street address.", tooLong: "This value is too long.",
  checkFields: "Check the highlighted fields.", fieldsRetained: "Your information is still here. Select an error to correct it.",
  failed: "We could not save the request.", saveError: "Saving is temporarily unavailable. Your bag is still here; try again with the same details.",
  unknownResult: "We could not confirm whether the request was saved. Retry with the same details to avoid duplicates.",
  stockChanged: "An item is unavailable or its quantity exceeds current stock. Return to the store and review your bag.",
  priceChanged: "Product prices changed. Review the updated estimate, then save again.",
  recovered: "Invalid saved bag data was removed. Review the remaining products before saving.",
  storage: "This browser cannot retain your shopping preferences. A saved request is still valid; copy its number before leaving.",
  continueShipping: "Continue to shipping", reviewButton: "Review request", back: "Back", free: "Free",
  standard: "Standard estimate", express: "Express estimate", priority: "Priority estimate",
  standardTiming: "Estimated 6–10 business days after dispatch", expressTiming: "Estimated 3–5 business days after dispatch",
  priorityTiming: "Estimated 2–3 business days after dispatch", timingNote: "Shipping options are estimates, not a dispatch promise.",
  paymentPending: "Payment activation pending", noCharge: "No charge", noCard: "No card or bank information is requested or stored.",
  noReservation: "This request is unpaid. Availability and the final price must be checked again before a future paid order.",
  saving: "Saving request…", save: "Save unpaid request", summary: "Request summary", editBag: "Edit bag",
  subtotal: "Products subtotal", shipping: "Shipping estimate", duties: "Import duties", notCalculated: "Not calculated",
  estimate: "Estimated total", dutyNote: "The estimate excludes import duties. Any final taxes and shipping must be confirmed before payment.",
  empty: "Your bag is empty.", emptyBody: "Choose products in the store before saving a request.", browse: "Browse products",
  saved: "Request saved", savedTitle: "Your unpaid request is saved.", savedBody: "Nothing was charged. Stock is not reserved and dispatch is not arranged.",
  orderNumber: "Request number", track: "Check this request", continueShopping: "Continue shopping", status: "Payment status: pending",
  inventory: "Current available quantity", remove: "Remove", routes: "Planned fulfillment routes", limit: "Maximum 10 per product",
  confirmPrevious: "Confirm the previous save", confirmPreviousBody: "An earlier save may have succeeded. Check its result using the original details before starting a different request.",
} as const;

type CopyKey = keyof typeof en;
const translations: Record<Exclude<StoreLocale, "en">, Record<CopyKey, string>> = {
  zh: {
    preparing: "正在加载最新商品…", unavailable: "商品目录暂时无法加载。", retry: "重试", loading: "请稍候",
    backStore: "返回商城", language: "语言", draft: "未付款订单需求", details: "收货信息", shippingMethod: "配送估算", review: "确认需求", step: "步骤",
    heading1: "希望送到哪里？", heading2: "选择配送估算。", heading3: "核对并保存购物需求。",
    paused: "在线支付尚未开通。保存需求不会扣款、不锁定库存，也不会安排发货。",
    contact: "联系方式", email: "邮箱", marketing: "接收新品与优惠信息。", addressTitle: "收货地址",
    firstName: "名字", lastName: "姓氏", country: "国家或地区", address: "街道地址", apartment: "公寓、房间号等（选填）",
    city: "城市", region: "州／省／地区", postal: "邮政编码", phone: "电话", required: "请填写此项。",
    invalidEmail: "请输入有效邮箱。", invalidPhone: "请输入有效电话号码。", invalidPostal: "请输入有效邮政编码。",
    invalidAddress: "请填写完整街道地址。", tooLong: "此项内容过长。", checkFields: "请检查标出的信息。",
    fieldsRetained: "已保留填写内容，点击错误提示可前往修改。", failed: "未能保存购物需求。",
    saveError: "保存暂时不可用。购物袋仍在，请使用相同信息重试。", unknownResult: "暂时无法确认需求是否保存成功。请使用相同信息重试，避免重复保存。",
    stockChanged: "有商品已下架、缺货或数量超过当前库存，请返回商城核对购物袋。", priceChanged: "商品价格有变化，请确认更新后的估算，再次保存。",
    recovered: "已清理异常的购物袋数据，保存前请确认剩余商品。", storage: "浏览器无法保留购物偏好。已保存的需求仍有效，离开前请复制订单号。",
    continueShipping: "继续查看配送", reviewButton: "核对需求", back: "返回", free: "免费", standard: "标准配送估算", express: "快捷配送估算", priority: "优先配送估算",
    standardTiming: "发货后预计 6–10 个工作日", expressTiming: "发货后预计 3–5 个工作日", priorityTiming: "发货后预计 2–3 个工作日",
    timingNote: "配送方式与时间仅为估算，不代表发货承诺。", paymentPending: "在线支付待开通", noCharge: "不会扣款",
    noCard: "不会要求或保存银行卡及账户信息。", noReservation: "需求尚未付款。未来生成已付款订单前，必须重新确认库存与最终价格。",
    saving: "正在保存需求…", save: "保存未付款需求", summary: "需求明细", editBag: "修改购物袋", subtotal: "商品小计", shipping: "运费估算", duties: "进口税费",
    notCalculated: "尚未计算", estimate: "预估总额", dutyNote: "估算不包含进口税费。最终税费与运费须在付款前确认。",
    empty: "购物袋为空。", emptyBody: "请先在商城选择商品，再保存购物需求。", browse: "浏览商品", saved: "需求已保存", savedTitle: "未付款需求已保存。",
    savedBody: "没有产生扣款，未锁定库存，也未安排发货。", orderNumber: "订单需求号", track: "查询此需求", continueShopping: "继续购物", status: "支付状态：待付款",
    inventory: "当前可售数量", remove: "移除", routes: "计划履约路线", limit: "每件商品最多 10 件",
    confirmPrevious: "确认上次保存结果", confirmPreviousBody: "上次保存可能已成功，请先使用当时的信息确认结果，再开始其他需求。",
  },
  es: {
    preparing: "Cargando los productos actuales…", unavailable: "Los productos no están disponibles temporalmente.", retry: "Reintentar", loading: "Espera un momento",
    backStore: "Volver a la tienda", language: "Idioma", draft: "Solicitud sin pagar", details: "Datos de entrega", shippingMethod: "Estimación de envío", review: "Revisar solicitud", step: "Paso",
    heading1: "¿Dónde quieres recibirlo?", heading2: "Elige una estimación de envío.", heading3: "Revisa y guarda tu solicitud.",
    paused: "El pago en línea aún no está activo. Guardar una solicitud no cobra, no reserva existencias ni programa el envío.",
    contact: "Contacto", email: "Correo electrónico", marketing: "Recibir novedades y ofertas.", addressTitle: "Dirección de entrega",
    firstName: "Nombre", lastName: "Apellidos", country: "País o región", address: "Dirección", apartment: "Apartamento, etc. (opcional)", city: "Ciudad", region: "Estado / región", postal: "Código postal", phone: "Teléfono",
    required: "Este campo es obligatorio.", invalidEmail: "Introduce un correo válido.", invalidPhone: "Introduce un teléfono válido.", invalidPostal: "Introduce un código postal válido.", invalidAddress: "Introduce una dirección completa.", tooLong: "El valor es demasiado largo.",
    checkFields: "Revisa los datos señalados.", fieldsRetained: "Conservamos los datos. Selecciona un error para corregirlo.", failed: "No pudimos guardar la solicitud.",
    saveError: "No se puede guardar ahora. La bolsa sigue aquí; reintenta con los mismos datos.", unknownResult: "No pudimos confirmar si se guardó. Reintenta con los mismos datos para evitar duplicados.",
    stockChanged: "Un producto no está disponible o supera las existencias. Vuelve a la tienda y revisa la bolsa.", priceChanged: "Los precios cambiaron. Revisa la estimación actualizada y vuelve a guardar.",
    recovered: "Eliminamos datos inválidos de la bolsa. Revisa los productos restantes.", storage: "Este navegador no conserva las preferencias. La solicitud guardada sigue siendo válida; copia su número antes de salir.",
    continueShipping: "Continuar al envío", reviewButton: "Revisar solicitud", back: "Volver", free: "Gratis", standard: "Estimación estándar", express: "Estimación exprés", priority: "Estimación prioritaria",
    standardTiming: "Estimado: 6–10 días hábiles tras el despacho", expressTiming: "Estimado: 3–5 días hábiles tras el despacho", priorityTiming: "Estimado: 2–3 días hábiles tras el despacho",
    timingNote: "Las opciones y plazos son estimaciones, no promesas de despacho.", paymentPending: "Pago pendiente de activación", noCharge: "Sin cargo", noCard: "No se solicita ni guarda información bancaria.",
    noReservation: "La solicitud está sin pagar. Las existencias y el precio final deben revisarse antes de un futuro pedido pagado.", saving: "Guardando solicitud…", save: "Guardar solicitud sin pagar", summary: "Resumen de la solicitud", editBag: "Editar bolsa",
    subtotal: "Subtotal de productos", shipping: "Envío estimado", duties: "Aranceles", notCalculated: "No calculados", estimate: "Total estimado", dutyNote: "La estimación excluye aranceles. Los impuestos y el envío finales deben confirmarse antes de pagar.",
    empty: "La bolsa está vacía.", emptyBody: "Elige productos en la tienda antes de guardar una solicitud.", browse: "Ver productos", saved: "Solicitud guardada", savedTitle: "Tu solicitud sin pagar está guardada.",
    savedBody: "No se cobró nada. No se reservaron existencias ni se programó el envío.", orderNumber: "Número de solicitud", track: "Consultar esta solicitud", continueShopping: "Seguir comprando", status: "Estado del pago: pendiente",
    inventory: "Cantidad disponible", remove: "Quitar", routes: "Rutas previstas", limit: "Máximo 10 por producto",
    confirmPrevious: "Confirmar el guardado anterior", confirmPreviousBody: "Puede que el intento anterior se guardara. Confirma su resultado con los datos originales antes de iniciar otra solicitud.",
  },
};

export function commerceCopy(locale: StoreLocale) {
  return locale === "en" ? en : translations[locale];
}
